---
Name: nswdpc-search-elasticsearch
---
# Specify custom search engines for the ExtensibleSearchPage
nglasl\extensible\ExtensibleSearchPage:
  custom_search_engines:
    Symbiote\ElasticSearch\ElasticaSearchEngine: 'Elastic'

nglasl\extensible\ExtensibleSearchSuggestion:
  enable_suggestions: true

# add extensions to controllers
PageController:
  extensions:
    - 'nglasl\extensible\ExtensibleSearchExtension'
    - 'Symbiote\ElasticSearch\ElasticaSearchController'

# add extensions to Page objects
Page:
  extensions:
    # pages are searchable
    - 'Symbiote\ElasticSearch\ElasticaSearchable'
    # pages can have taxonomy
    - 'Symbiote\ElasticSearch\DataDiscovery'
